# Connection to PostgreSQL DB;

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha-backend
    username: rinha
    password: backend
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
